"""
dynamic_race_situation.py

PHASE 4.2 — DYNAMIC RACE SITUATION ANALYSIS

Purpose
-------
Convert the dynamic race state generated by Phase 4.1
into a strategic interpretation.

This module evaluates:

    Position status
    Tyre condition
    Pace trend
    Degradation level
    Pit urgency
    Race stage
    Threat level
    Opportunity
    Overall race situation

Input
-----

Dictionary generated by:

    build_dynamic_race_state()

Output
------

Structured strategic situation that can later be consumed
by advanced Phase 4 strategy modules.
"""

from typing import Dict, Any


# ============================================================
# INPUT VALIDATION
# ============================================================

def validate_dynamic_race_state(
    race_state: Dict[str, Any]
) -> None:
    """
    Validate the dynamic race state received from Phase 4.1.
    """

    if not isinstance(
        race_state,
        dict
    ):

        raise TypeError(
            "race_state must be a dictionary."
        )

    if not race_state:

        raise ValueError(
            "race_state cannot be empty."
        )

    required_fields = [

        "CurrentLap",

        "TotalLaps",

        "LapsRemaining",

        "Position",

        "TyreCompound",

        "TyreLife",

        "RecentPace",

        "AveragePace",

        "DegradationRate"

    ]

    for field in required_fields:

        if field not in race_state:

            raise ValueError(

                f"Missing required race-state "
                f"field: {field}"

            )


# ============================================================
# RACE STAGE
# ============================================================

def determine_race_stage(
    race_state: Dict[str, Any]
) -> str:
    """
    Determine the current stage of the race.
    """

    progress = race_state.get(
        "RaceProgress"
    )

    if progress is None:

        return "UNKNOWN"

    if progress < 0.25:

        return "EARLY"

    if progress < 0.65:

        return "MID"

    if progress < 0.85:

        return "LATE"

    return "FINAL"


# ============================================================
# POSITION STATUS
# ============================================================

def determine_position_status(
    race_state: Dict[str, Any]
) -> str:
    """
    Convert numerical position into strategic position status.
    """

    position = race_state.get(
        "Position"
    )

    if position is None:

        return "UNKNOWN"

    if position == 1:

        return "LEADING"

    if position <= 3:

        return "PODIUM"

    if position <= 10:

        return "POINTS"

    if position <= 15:

        return "MIDFIELD"

    return "BACKMARKER"


# ============================================================
# TYRE STATUS
# ============================================================

def determine_tyre_status(
    race_state: Dict[str, Any]
) -> str:
    """
    Estimate tyre condition primarily from tyre age
    and degradation rate.
    """

    tyre_age = race_state.get(
        "TyreLife"
    )

    degradation = race_state.get(
        "DegradationRate"
    )

    if tyre_age is None:

        return "UNKNOWN"

    if degradation is None:

        degradation = 0.0

    # --------------------------------------------------------
    # CRITICAL CONDITION
    # --------------------------------------------------------

    if (
        tyre_age >= 30
        or degradation >= 0.18
    ):

        return "CRITICAL"

    # --------------------------------------------------------
    # AGING CONDITION
    # --------------------------------------------------------

    if (
        tyre_age >= 20
        or degradation >= 0.10
    ):

        return "AGING"

    # --------------------------------------------------------
    # NORMAL / HEALTHY
    # --------------------------------------------------------

    return "HEALTHY"


# ============================================================
# PACE STATUS
# ============================================================

def determine_pace_status(
    race_state: Dict[str, Any]
) -> str:
    """
    Compare recent pace with longer-term average pace.

    Lower lap time = faster pace.
    """

    recent_pace = race_state.get(
        "RecentPace"
    )

    average_pace = race_state.get(
        "AveragePace"
    )

    if (
        recent_pace is None
        or average_pace is None
    ):

        return "UNKNOWN"

    difference = (

        float(recent_pace)

        -

        float(average_pace)

    )

    # Recent pace is meaningfully quicker

    if difference <= -0.40:

        return "IMPROVING"

    # Recent pace is meaningfully slower

    if difference >= 0.40:

        return "DECLINING"

    return "STABLE"


# ============================================================
# DEGRADATION STATUS
# ============================================================

def determine_degradation_status(
    race_state: Dict[str, Any]
) -> str:
    """
    Classify degradation rate.
    """

    degradation = race_state.get(
        "DegradationRate"
    )

    if degradation is None:

        return "UNKNOWN"

    degradation = float(
        degradation
    )

    if degradation < 0:

        return "IMPROVING"

    if degradation < 0.05:

        return "LOW"

    if degradation < 0.12:

        return "MODERATE"

    if degradation < 0.20:

        return "HIGH"

    return "CRITICAL"


# ============================================================
# PIT URGENCY
# ============================================================

def determine_pit_urgency(
    race_state: Dict[str, Any],
    tyre_status: str,
    degradation_status: str
) -> str:
    """
    Estimate how urgently a pit stop should be considered.
    """

    remaining_laps = race_state.get(
        "LapsRemaining"
    )

    if remaining_laps is None:

        return "UNKNOWN"

    if remaining_laps <= 3:

        return "NONE"

    if (
        tyre_status == "CRITICAL"
        or degradation_status == "CRITICAL"
    ):

        return "HIGH"

    if (
        tyre_status == "AGING"
        or degradation_status == "HIGH"
    ):

        return "MEDIUM"

    return "LOW"


# ============================================================
# THREAT LEVEL
# ============================================================

def determine_threat_level(
    race_state: Dict[str, Any],
    pace_status: str,
    tyre_status: str
) -> str:
    """
    Estimate strategic threat level.

    Phase 4.2 does not yet contain full gap/traffic modelling,
    so threat is currently based on track position, tyre
    condition and pace behaviour.
    """

    position = race_state.get(
        "Position"
    )

    if position is None:

        return "UNKNOWN"

    if (
        tyre_status == "CRITICAL"
        and pace_status == "DECLINING"
    ):

        return "HIGH"

    if (
        tyre_status == "AGING"
        or pace_status == "DECLINING"
    ):

        return "MEDIUM"

    if position <= 3:

        return "LOW"

    return "NORMAL"


# ============================================================
# OPPORTUNITY
# ============================================================

def determine_opportunity(
    race_state: Dict[str, Any],
    pace_status: str,
    tyre_status: str
) -> str:
    """
    Determine the broad strategic opportunity.
    """

    position = race_state.get(
        "Position"
    )

    remaining_laps = race_state.get(
        "LapsRemaining"
    )

    if (
        position is None
        or remaining_laps is None
    ):

        return "UNKNOWN"

    if position == 1:

        if tyre_status == "HEALTHY":

            return "CONTROL_RACE"

        return "DEFEND_LEAD"

    if (
        position <= 3
        and pace_status == "IMPROVING"
    ):

        return "ATTACK_LEAD"

    if (
        position <= 10
        and pace_status == "IMPROVING"
    ):

        return "ATTACK_POSITION"

    if (
        tyre_status in [
            "AGING",
            "CRITICAL"
        ]
    ):

        return "PIT_WINDOW"

    return "MAINTAIN_POSITION"


# ============================================================
# OVERALL RACE SITUATION
# ============================================================

def determine_race_situation(
    position_status: str,
    tyre_status: str,
    pace_status: str,
    threat_level: str,
    opportunity: str
) -> str:
    """
    Convert component analyses into one high-level strategic
    race situation.
    """

    if tyre_status == "CRITICAL":

        return "TYRE_MANAGEMENT_CRITICAL"

    if threat_level == "HIGH":

        return "DEFENSIVE_PRESSURE"

    if opportunity in [

        "ATTACK_LEAD",
        "ATTACK_POSITION"

    ]:

        return "ATTACKING"

    if opportunity == "CONTROL_RACE":

        return "RACE_CONTROL"

    if opportunity == "DEFEND_LEAD":

        return "DEFENDING_LEAD"

    if opportunity == "PIT_WINDOW":

        return "STRATEGIC_PIT_WINDOW"

    if position_status in [

        "LEADING",
        "PODIUM"

    ]:

        return "STRONG_POSITION"

    return "NEUTRAL"


# ============================================================
# STRATEGIC SUMMARY
# ============================================================

def build_strategic_summary(
    race_state: Dict[str, Any],
    race_stage: str,
    position_status: str,
    tyre_status: str,
    pace_status: str,
    pit_urgency: str,
    race_situation: str
) -> str:
    """
    Generate a short human-readable strategic summary.
    """

    driver = race_state.get(
        "Driver",
        "Driver"
    )

    position = race_state.get(
        "Position"
    )

    compound = race_state.get(
        "TyreCompound",
        "UNKNOWN"
    )

    tyre_age = race_state.get(
        "TyreLife"
    )

    current_lap = race_state.get(
        "CurrentLap"
    )

    total_laps = race_state.get(
        "TotalLaps"
    )

    summary = (

        f"{driver} is running P{position} "

        f"on {compound} tyres "

        f"at lap {current_lap}/{total_laps}. "

        f"The tyres are classified as "
        f"{tyre_status.lower()} "

        f"with a {pace_status.lower()} "
        f"pace trend. "

        f"Pit urgency is "
        f"{pit_urgency.lower()} "

        f"and the current strategic state is "
        f"{race_situation.lower()}."

    )

    return summary


# ============================================================
# COMPLETE DYNAMIC RACE SITUATION ANALYSIS
# ============================================================

def analyze_dynamic_race_situation(
    race_state: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Run the complete Phase 4.2 dynamic race-situation analysis.
    """

    validate_dynamic_race_state(
        race_state
    )

    # --------------------------------------------------------
    # RACE STAGE
    # --------------------------------------------------------

    race_stage = determine_race_stage(
        race_state
    )

    # --------------------------------------------------------
    # POSITION
    # --------------------------------------------------------

    position_status = (
        determine_position_status(
            race_state
        )
    )

    # --------------------------------------------------------
    # TYRE
    # --------------------------------------------------------

    tyre_status = determine_tyre_status(
        race_state
    )

    # --------------------------------------------------------
    # PACE
    # --------------------------------------------------------

    pace_status = determine_pace_status(
        race_state
    )

    # --------------------------------------------------------
    # DEGRADATION
    # --------------------------------------------------------

    degradation_status = (
        determine_degradation_status(
            race_state
        )
    )

    # --------------------------------------------------------
    # PIT URGENCY
    # --------------------------------------------------------

    pit_urgency = determine_pit_urgency(

        race_state,

        tyre_status,

        degradation_status

    )

    # --------------------------------------------------------
    # THREAT
    # --------------------------------------------------------

    threat_level = determine_threat_level(

        race_state,

        pace_status,

        tyre_status

    )

    # --------------------------------------------------------
    # OPPORTUNITY
    # --------------------------------------------------------

    opportunity = determine_opportunity(

        race_state,

        pace_status,

        tyre_status

    )

    # --------------------------------------------------------
    # OVERALL SITUATION
    # --------------------------------------------------------

    race_situation = (
        determine_race_situation(

            position_status,

            tyre_status,

            pace_status,

            threat_level,

            opportunity

        )
    )

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    strategic_summary = (
        build_strategic_summary(

            race_state,

            race_stage,

            position_status,

            tyre_status,

            pace_status,

            pit_urgency,

            race_situation

        )
    )

    # ========================================================
    # FINAL RESULT
    # ========================================================

    return {

        "driver":
            race_state.get(
                "Driver"
            ),

        "current_lap":
            race_state.get(
                "CurrentLap"
            ),

        "total_laps":
            race_state.get(
                "TotalLaps"
            ),

        "laps_remaining":
            race_state.get(
                "LapsRemaining"
            ),

        "position":
            race_state.get(
                "Position"
            ),

        "tyre_compound":
            race_state.get(
                "TyreCompound"
            ),

        "tyre_life":
            race_state.get(
                "TyreLife"
            ),

        "recent_pace":
            race_state.get(
                "RecentPace"
            ),

        "average_pace":
            race_state.get(
                "AveragePace"
            ),

        "degradation_rate":
            race_state.get(
                "DegradationRate"
            ),

        "race_stage":
            race_stage,

        "position_status":
            position_status,

        "tyre_status":
            tyre_status,

        "pace_status":
            pace_status,

        "degradation_status":
            degradation_status,

        "pit_urgency":
            pit_urgency,

        "threat_level":
            threat_level,

        "opportunity":
            opportunity,

        "race_situation":
            race_situation,

        "strategic_summary":
            strategic_summary

    }


# ============================================================
# DISPLAY
# ============================================================

def display_dynamic_race_situation(
    situation: Dict[str, Any]
) -> None:
    """
    Display dynamic strategic interpretation.
    """

    print(
        "\n" + "=" * 65
    )

    print(
        "PHASE 4.2 — DYNAMIC RACE SITUATION"
    )

    print(
        "=" * 65
    )

    print(
        f"Driver: "
        f"{situation.get('driver')}"
    )

    print(
        f"Lap: "
        f"{situation.get('current_lap')}"
        f"/"
        f"{situation.get('total_laps')}"
    )

    print(
        f"Position: "
        f"P{situation.get('position')}"
    )

    print(
        f"Tyre: "
        f"{situation.get('tyre_compound')}"
    )

    print(
        f"Tyre Life: "
        f"{situation.get('tyre_life')}"
    )

    print(
        "-" * 65
    )

    print(
        f"Race Stage: "
        f"{situation.get('race_stage')}"
    )

    print(
        f"Position Status: "
        f"{situation.get('position_status')}"
    )

    print(
        f"Tyre Status: "
        f"{situation.get('tyre_status')}"
    )

    print(
        f"Pace Status: "
        f"{situation.get('pace_status')}"
    )

    print(
        f"Degradation: "
        f"{situation.get('degradation_status')}"
    )

    print(
        f"Pit Urgency: "
        f"{situation.get('pit_urgency')}"
    )

    print(
        f"Threat Level: "
        f"{situation.get('threat_level')}"
    )

    print(
        f"Opportunity: "
        f"{situation.get('opportunity')}"
    )

    print(
        "-" * 65
    )

    print(
        f"Race Situation: "
        f"{situation.get('race_situation')}"
    )

    print(
        "\nStrategic Summary:"
    )

    print(
        situation.get(
            "strategic_summary"
        )
    )

    print(
        "=" * 65
    )