"""
dynamic_tyre_strategy.py

PHASE 4.3 — DYNAMIC TYRE STRATEGY ENGINE

Purpose
-------
Evaluate tyre strategy options using the dynamically
reconstructed race state generated by Phase 4.1 and the
strategic interpretation generated by Phase 4.2.

Unlike the historical fallback used in Phase 3, this module
uses the actual state of the race at the selected lap.

Candidate options:

    STAY OUT
    PIT -> SOFT
    PIT -> MEDIUM
    PIT -> HARD

The engine evaluates:

    Current tyre
    Current tyre age
    Remaining laps
    Current pace
    Degradation
    Pit-stop loss
    Race situation

and ranks the available tyre strategies.
"""

from typing import Dict, Any, List

from src.strategy.tyre_stint import (
    analyze_tyre_stint
)


# ============================================================
# CONSTANTS
# ============================================================

DEFAULT_PIT_LOSS = 22.0

AVAILABLE_COMPOUNDS = [

    "SOFT",

    "MEDIUM",

    "HARD"

]


# ============================================================
# INPUT VALIDATION
# ============================================================

def validate_dynamic_tyre_inputs(
    race_state: Dict[str, Any],
    race_situation: Dict[str, Any]
) -> None:
    """
    Validate Phase 4.1 and Phase 4.2 inputs.
    """

    if not isinstance(
        race_state,
        dict
    ):

        raise TypeError(
            "race_state must be a dictionary."
        )

    if not race_state:

        raise ValueError(
            "race_state cannot be empty."
        )

    if not isinstance(
        race_situation,
        dict
    ):

        raise TypeError(
            "race_situation must be a dictionary."
        )

    if not race_situation:

        raise ValueError(
            "race_situation cannot be empty."
        )

    required_state_fields = [

        "CurrentLap",

        "TotalLaps",

        "LapsRemaining",

        "TyreCompound",

        "TyreLife",

        "RecentPace"

    ]

    for field in required_state_fields:

        if field not in race_state:

            raise ValueError(

                f"Missing required race-state "
                f"field: {field}"

            )

    if race_state["LapsRemaining"] <= 0:

        raise ValueError(
            "Dynamic tyre strategy requires "
            "at least one remaining lap."
        )


# ============================================================
# DETERMINE PIT LOSS
# ============================================================

def determine_pit_loss(
    race_state: Dict[str, Any]
) -> float:
    """
    Determine estimated pit-stop loss.

    Uses race-state PitLoss when available,
    otherwise falls back to the current Phase 4
    baseline value.
    """

    pit_loss = race_state.get(
        "PitLoss"
    )

    if pit_loss is None:

        pit_loss = DEFAULT_PIT_LOSS

    return float(
        pit_loss
    )


# ============================================================
# SIMULATE STAY-OUT OPTION
# ============================================================

def evaluate_stay_out(
    base_lap_time: float,
    current_tyre: str,
    tyre_age: int,
    remaining_laps: int
) -> Dict[str, Any]:
    """
    Evaluate completing the remaining race
    on the current tyre.
    """

    stint = analyze_tyre_stint(

        base_lap_time=base_lap_time,

        compound=current_tyre,

        tyre_age=tyre_age,

        stint_length=remaining_laps

    )

    total_time = float(
        stint["TotalStintTime"]
    )

    return {

        "action":
            "STAY_OUT",

        "compound":
            current_tyre,

        "tyre_plan":
            current_tyre,

        "starting_tyre_age":
            int(tyre_age),

        "stint_length":
            int(remaining_laps),

        "pit_loss":
            0.0,

        "projected_stint_time":
            round(
                total_time,
                3
            ),

        "projected_total_time":
            round(
                total_time,
                3
            ),

        "average_lap_time":
            round(
                float(
                    stint["AverageLapTime"]
                ),
                3
            ),

        "degradation_impact":
            round(
                float(
                    stint["DegradationImpact"]
                ),
                3
            ),

        "degradation_evaluation":
            stint.get(
                "DegradationEvaluation",
                "UNKNOWN"
            )

    }


# ============================================================
# SIMULATE PIT OPTION
# ============================================================

def evaluate_pit_option(
    base_lap_time: float,
    compound: str,
    remaining_laps: int,
    pit_loss: float
) -> Dict[str, Any]:
    """
    Evaluate making a pit stop and fitting
    a fresh tyre compound.
    """

    stint = analyze_tyre_stint(

        base_lap_time=base_lap_time,

        compound=compound,

        tyre_age=0,

        stint_length=remaining_laps

    )

    stint_time = float(
        stint["TotalStintTime"]
    )

    total_time = (

        stint_time

        +

        pit_loss

    )

    return {

        "action":
            "PIT",

        "compound":
            compound,

        "tyre_plan":
            f"PIT -> {compound}",

        "starting_tyre_age":
            0,

        "stint_length":
            int(remaining_laps),

        "pit_loss":
            round(
                float(pit_loss),
                3
            ),

        "projected_stint_time":
            round(
                stint_time,
                3
            ),

        "projected_total_time":
            round(
                total_time,
                3
            ),

        "average_lap_time":
            round(
                float(
                    stint["AverageLapTime"]
                ),
                3
            ),

        "degradation_impact":
            round(
                float(
                    stint["DegradationImpact"]
                ),
                3
            ),

        "degradation_evaluation":
            stint.get(
                "DegradationEvaluation",
                "UNKNOWN"
            )

    }


# ============================================================
# GENERATE ALL TYRE OPTIONS
# ============================================================

def generate_dynamic_tyre_options(
    race_state: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Generate every available tyre strategy from
    the selected race lap.
    """

    base_lap_time = float(
        race_state[
            "RecentPace"
        ]
    )

    current_tyre = str(
        race_state[
            "TyreCompound"
        ]
    ).upper()

    tyre_age = int(
        race_state[
            "TyreLife"
        ]
    )

    remaining_laps = int(
        race_state[
            "LapsRemaining"
        ]
    )

    pit_loss = determine_pit_loss(
        race_state
    )

    strategies = []

    # --------------------------------------------------------
    # OPTION 1
    # STAY OUT
    # --------------------------------------------------------

    stay_out = evaluate_stay_out(

        base_lap_time=base_lap_time,

        current_tyre=current_tyre,

        tyre_age=tyre_age,

        remaining_laps=remaining_laps

    )

    strategies.append(
        stay_out
    )

    # --------------------------------------------------------
    # OPTIONS 2–4
    # PIT FOR FRESH TYRES
    # --------------------------------------------------------

    for compound in AVAILABLE_COMPOUNDS:

        pit_option = evaluate_pit_option(

            base_lap_time=base_lap_time,

            compound=compound,

            remaining_laps=remaining_laps,

            pit_loss=pit_loss

        )

        strategies.append(
            pit_option
        )

    return strategies


# ============================================================
# RANK STRATEGIES
# ============================================================

def rank_dynamic_tyre_options(
    strategies: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Rank tyre options according to projected
    remaining-race time.

    Lower time = better strategy.
    """

    if not strategies:

        return []

    ranked = sorted(

        strategies,

        key=lambda strategy:
        strategy[
            "projected_total_time"
        ]

    )

    best_time = ranked[0][
        "projected_total_time"
    ]

    for rank, strategy in enumerate(

        ranked,

        start=1

    ):

        strategy[
            "strategy_rank"
        ] = rank

        strategy[
            "time_difference"
        ] = round(

            strategy[
                "projected_total_time"
            ]

            -

            best_time,

            3

        )

    return ranked


# ============================================================
# DETERMINE STRATEGY CONFIDENCE
# ============================================================

def calculate_strategy_confidence(
    strategies: List[Dict[str, Any]]
) -> float:
    """
    Estimate confidence from the projected gap
    between the best and second-best tyre options.
    """

    if len(strategies) < 2:

        return 50.0

    difference = (

        strategies[1][
            "projected_total_time"
        ]

        -

        strategies[0][
            "projected_total_time"
        ]

    )

    confidence = (

        60.0

        +

        difference * 8.0

    )

    confidence = max(

        50.0,

        min(
            99.0,
            confidence
        )

    )

    return round(
        confidence,
        1
    )


# ============================================================
# BUILD RECOMMENDATION REASON
# ============================================================

def build_tyre_reason(
    best_strategy: Dict[str, Any],
    race_state: Dict[str, Any],
    race_situation: Dict[str, Any]
) -> str:
    """
    Generate a readable explanation for the selected
    dynamic tyre strategy.
    """

    compound = best_strategy[
        "compound"
    ]

    action = best_strategy[
        "action"
    ]

    remaining_laps = race_state.get(
        "LapsRemaining"
    )

    tyre_status = race_situation.get(
        "tyre_status",
        "UNKNOWN"
    )

    pace_status = race_situation.get(
        "pace_status",
        "UNKNOWN"
    )

    if action == "STAY_OUT":

        return (

            f"Staying on the current {compound} tyre "
            f"produces the lowest projected time for "
            f"the remaining {remaining_laps} laps. "
            f"The current tyre condition is classified "
            f"as {tyre_status.lower()} and the pace "
            f"trend is {pace_status.lower()}."

        )

    return (

        f"Pitting for fresh {compound} tyres produces "
        f"the lowest projected remaining-race time "
        f"after accounting for pit-stop loss. "
        f"There are {remaining_laps} laps remaining, "
        f"while the current tyre condition is "
        f"{tyre_status.lower()} and the current pace "
        f"trend is {pace_status.lower()}."

    )


# ============================================================
# COMPLETE PHASE 4.3 ENGINE
# ============================================================

def generate_dynamic_tyre_strategy(
    race_state: Dict[str, Any],
    race_situation: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Run the complete Phase 4.3 dynamic tyre strategy engine.
    """

    validate_dynamic_tyre_inputs(

        race_state,

        race_situation

    )

    # --------------------------------------------------------
    # GENERATE OPTIONS
    # --------------------------------------------------------

    strategies = generate_dynamic_tyre_options(
        race_state
    )

    if not strategies:

        raise RuntimeError(
            "No dynamic tyre strategies were generated."
        )

    # --------------------------------------------------------
    # RANK OPTIONS
    # --------------------------------------------------------

    ranked_strategies = (
        rank_dynamic_tyre_options(
            strategies
        )
    )

    best_strategy = (
        ranked_strategies[0]
    )

    # --------------------------------------------------------
    # CONFIDENCE
    # --------------------------------------------------------

    confidence = (
        calculate_strategy_confidence(
            ranked_strategies
        )
    )

    # --------------------------------------------------------
    # REASON
    # --------------------------------------------------------

    reason = build_tyre_reason(

        best_strategy,

        race_state,

        race_situation

    )

    # ========================================================
    # FINAL RESPONSE
    # ========================================================

    return {

        "current_lap":
            int(
                race_state[
                    "CurrentLap"
                ]
            ),

        "remaining_laps":
            int(
                race_state[
                    "LapsRemaining"
                ]
            ),

        "current_tyre":
            race_state[
                "TyreCompound"
            ],

        "current_tyre_age":
            race_state[
                "TyreLife"
            ],

        "race_situation":
            race_situation.get(
                "race_situation"
            ),

        "recommendation":
            (
                "STAY OUT"

                if best_strategy[
                    "action"
                ] == "STAY_OUT"

                else "PIT"
            ),

        "recommended_compound":
            best_strategy[
                "compound"
            ],

        "recommended_tyre_plan":
            best_strategy[
                "tyre_plan"
            ],

        "projected_total_time":
            best_strategy[
                "projected_total_time"
            ],

        "expected_advantage":
            (
                ranked_strategies[1][
                    "time_difference"
                ]

                if len(
                    ranked_strategies
                ) > 1

                else 0.0
            ),

        "confidence":
            confidence,

        "reason":
            reason,

        "best_strategy":
            best_strategy,

        "strategy_count":
            len(
                ranked_strategies
            ),

        "strategies":
            ranked_strategies

    }


# ============================================================
# DISPLAY
# ============================================================

def display_dynamic_tyre_strategy(
    result: Dict[str, Any]
) -> None:
    """
    Display Phase 4.3 tyre strategy results.
    """

    print(
        "\n" + "=" * 72
    )

    print(
        "PHASE 4.3 — DYNAMIC TYRE STRATEGY"
    )

    print(
        "=" * 72
    )

    print(
        f"Current Lap: "
        f"{result.get('current_lap')}"
    )

    print(
        f"Remaining Laps: "
        f"{result.get('remaining_laps')}"
    )

    print(
        f"Current Tyre: "
        f"{result.get('current_tyre')}"
    )

    print(
        f"Current Tyre Age: "
        f"{result.get('current_tyre_age')}"
    )

    print(
        "-" * 72
    )

    print(
        f"Recommendation: "
        f"{result.get('recommendation')}"
    )

    print(
        f"Recommended Compound: "
        f"{result.get('recommended_compound')}"
    )

    print(
        f"Tyre Plan: "
        f"{result.get('recommended_tyre_plan')}"
    )

    print(
        f"Projected Time: "
        f"{result.get('projected_total_time')}s"
    )

    print(
        f"Expected Advantage: "
        f"{result.get('expected_advantage')}s"
    )

    print(
        f"Confidence: "
        f"{result.get('confidence')}%"
    )

    print(
        "\nReason:"
    )

    print(
        result.get(
            "reason"
        )
    )

    print(
        "\n" + "-" * 72
    )

    print(
        "TYRE STRATEGY COMPARISON"
    )

    print(
        "-" * 72
    )

    for strategy in result.get(
        "strategies",
        []
    ):

        print(

            f"Rank "
            f"{strategy['strategy_rank']} | "

            f"{strategy['tyre_plan']:<15} | "

            f"Time: "
            f"{strategy['projected_total_time']:.3f}s | "

            f"Diff: "
            f"+{strategy['time_difference']:.3f}s | "

            f"Avg Lap: "
            f"{strategy['average_lap_time']:.3f}s"

        )

    print(
        "=" * 72
    )