"""
dynamic_strategy_scoring.py

PHASE 4.6 — DYNAMIC STRATEGY SCORING

Purpose
-------
Score and rank the dynamically simulated race strategies
generated by Phase 4.5.

The Phase 3 strategy scoring engine already evaluates:

    Pace
    Tyre Performance
    Pit Cost
    Traffic
    Track Position
    Degradation
    Risk

Phase 4.6 adds dynamic race-context awareness using:

    Current Race Situation
    Phase 4.3 Tyre Recommendation
    Phase 4.4 Pit Decision

Pipeline
--------

Dynamic Race State
        ↓
Dynamic Race Situation
        ↓
Dynamic Tyre Strategy
        ↓
Dynamic Pit Decision
        ↓
Dynamic Strategy Simulation
        ↓
Base Strategy Scoring
        ↓
Dynamic Context Score
        ↓
Dynamic Overall Score
        ↓
Final Dynamic Ranking
"""

from typing import Dict, Any, List

from src.strategy.strategy_scoring import (
    run_strategy_scoring
)


# ============================================================
# SCORE WEIGHTS
# ============================================================

BASE_SCORE_WEIGHT = 0.85

DYNAMIC_CONTEXT_WEIGHT = 0.15


# ============================================================
# HELPERS
# ============================================================

def _normalize_text(
    value
) -> str:
    """
    Normalize text values for comparison.
    """

    if value is None:

        return ""

    return (
        str(value)
        .strip()
        .upper()
        .replace("_", " ")
    )


# ============================================================
# INPUT VALIDATION
# ============================================================

def validate_dynamic_scoring_inputs(
    simulation_result: Dict[str, Any],
    race_state: Dict[str, Any],
    race_situation: Dict[str, Any],
    tyre_strategy: Dict[str, Any],
    pit_decision: Dict[str, Any]
) -> None:
    """
    Validate inputs required by Phase 4.6.
    """

    if not simulation_result:

        raise ValueError(
            "simulation_result cannot be empty."
        )


    if not race_state:

        raise ValueError(
            "race_state cannot be empty."
        )


    if not race_situation:

        raise ValueError(
            "race_situation cannot be empty."
        )


    if not tyre_strategy:

        raise ValueError(
            "tyre_strategy cannot be empty."
        )


    if not pit_decision:

        raise ValueError(
            "pit_decision cannot be empty."
        )


    strategies = simulation_result.get(
        "strategies",
        []
    )


    if not strategies:

        raise ValueError(
            "No simulated strategies were supplied."
        )


# ============================================================
# PIT-DECISION ALIGNMENT
# ============================================================

def calculate_decision_alignment_score(
    strategy: Dict[str, Any],
    pit_decision: Dict[str, Any]
) -> float:
    """
    Measure how closely a strategy agrees with
    the Phase 4.4 pit-stop decision.
    """

    decision = _normalize_text(

        pit_decision.get(
            "decision"
        )

        or

        pit_decision.get(
            "action"
        )

    )


    strategy_action = _normalize_text(

        strategy.get(
            "strategy"
        )

    )


    recommended_tyre = _normalize_text(

        pit_decision.get(
            "recommended_tyre"
        )

    )


    final_tyre = _normalize_text(

        strategy.get(
            "final_tyre"
        )

    )


    # ========================================================
    # STAY OUT
    # ========================================================

    if decision == "STAY OUT":

        if strategy_action == "STAY OUT":

            return 100.0

        return 65.0


    # ========================================================
    # PIT
    # ========================================================

    if decision in {
        "PIT",
        "PIT NOW"
    }:

        if strategy_action != "PIT":

            return 60.0


        if (
            recommended_tyre
            and
            final_tyre == recommended_tyre
        ):

            return 100.0


        return 82.0


    # ========================================================
    # UNKNOWN / NEUTRAL
    # ========================================================

    return 85.0


# ============================================================
# TYRE-STRATEGY ALIGNMENT
# ============================================================

def calculate_tyre_alignment_score(
    strategy: Dict[str, Any],
    tyre_strategy: Dict[str, Any]
) -> float:
    """
    Measure alignment with the tyre recommendation
    produced by Phase 4.3.
    """

    recommendation = _normalize_text(

        tyre_strategy.get(
            "Recommendation"
        )

        or

        tyre_strategy.get(
            "recommendation"
        )

    )


    recommended_compound = _normalize_text(

        tyre_strategy.get(
            "Compound"
        )

        or

        tyre_strategy.get(
            "recommended_compound"
        )

        or

        tyre_strategy.get(
            "recommended_tyre"
        )

    )


    strategy_action = _normalize_text(

        strategy.get(
            "strategy"
        )

    )


    final_tyre = _normalize_text(

        strategy.get(
            "final_tyre"
        )

    )


    # --------------------------------------------------------
    # STAY OUT RECOMMENDATION
    # --------------------------------------------------------

    if recommendation == "STAY OUT":

        if strategy_action == "STAY OUT":

            return 100.0


        if (
            recommended_compound
            and
            final_tyre == recommended_compound
        ):

            return 78.0


        return 70.0


    # --------------------------------------------------------
    # PIT RECOMMENDATION
    # --------------------------------------------------------

    if recommendation in {
        "PIT",
        "PIT NOW"
    }:

        if (
            strategy_action == "PIT"
            and
            final_tyre == recommended_compound
        ):

            return 100.0


        if strategy_action == "PIT":

            return 82.0


        return 65.0


    # --------------------------------------------------------
    # COMPOUND-ONLY MATCH
    # --------------------------------------------------------

    if (
        recommended_compound
        and
        final_tyre == recommended_compound
    ):

        return 95.0


    return 80.0


# ============================================================
# RACE-SITUATION SCORE
# ============================================================

def calculate_race_situation_score(
    strategy: Dict[str, Any],
    race_situation: Dict[str, Any]
) -> float:
    """
    Evaluate how suitable a strategy is for the
    reconstructed strategic race situation.
    """

    situation = _normalize_text(

        race_situation.get(
            "race_situation"
        )

        or

        race_situation.get(
            "RaceSituation"
        )

        or

        race_situation.get(
            "situation"
        )

    )


    strategy_action = _normalize_text(

        strategy.get(
            "strategy"
        )

    )


    # ========================================================
    # RACE CONTROL
    # ========================================================

    if situation == "RACE CONTROL":

        if strategy_action == "STAY OUT":

            return 100.0

        return 82.0


    # ========================================================
    # DEFENSIVE SITUATION
    # ========================================================

    if situation in {

        "DEFENSIVE",

        "DEFEND",

        "UNDER THREAT"

    }:

        if strategy_action == "PIT":

            return 88.0

        return 92.0


    # ========================================================
    # ATTACK
    # ========================================================

    if situation in {

        "ATTACK",

        "ATTACKING",

        "OPPORTUNITY"

    }:

        if strategy_action == "PIT":

            return 95.0

        return 85.0


    # ========================================================
    # HIGH PIT URGENCY
    # ========================================================

    pit_urgency = _normalize_text(

        race_situation.get(
            "pit_urgency"
        )

    )


    if pit_urgency == "HIGH":

        if strategy_action == "PIT":

            return 100.0

        return 65.0


    if pit_urgency == "MEDIUM":

        if strategy_action == "PIT":

            return 90.0

        return 88.0


    # ========================================================
    # NEUTRAL
    # ========================================================

    return 90.0


# ============================================================
# DYNAMIC CONTEXT SCORE
# ============================================================

def calculate_dynamic_context_score(
    strategy: Dict[str, Any],
    race_situation: Dict[str, Any],
    tyre_strategy: Dict[str, Any],
    pit_decision: Dict[str, Any]
) -> Dict[str, float]:
    """
    Calculate dynamic context scores.
    """

    decision_score = (
        calculate_decision_alignment_score(

            strategy=strategy,

            pit_decision=pit_decision

        )
    )


    tyre_score = (
        calculate_tyre_alignment_score(

            strategy=strategy,

            tyre_strategy=tyre_strategy

        )
    )


    situation_score = (
        calculate_race_situation_score(

            strategy=strategy,

            race_situation=race_situation

        )
    )


    context_score = (

        decision_score
        +
        tyre_score
        +
        situation_score

    ) / 3


    return {

        "decision_alignment_score":
            round(
                decision_score,
                2
            ),

        "tyre_alignment_score":
            round(
                tyre_score,
                2
            ),

        "race_situation_score":
            round(
                situation_score,
                2
            ),

        "dynamic_context_score":
            round(
                context_score,
                2
            )

    }


# ============================================================
# DYNAMIC OVERALL SCORE
# ============================================================

def calculate_dynamic_overall_score(
    base_score: float,
    context_score: float
) -> float:
    """
    Combine Phase 3 unified scoring with
    Phase 4 dynamic context.
    """

    score = (

        float(
            base_score
        )
        *
        BASE_SCORE_WEIGHT

        +

        float(
            context_score
        )
        *
        DYNAMIC_CONTEXT_WEIGHT

    )


    return round(

        max(
            0.0,
            min(
                100.0,
                score
            )
        ),

        2

    )


# ============================================================
# SCORE DYNAMIC STRATEGIES
# ============================================================

def score_dynamic_strategies(
    strategies: List[Dict[str, Any]],
    race_situation: Dict[str, Any],
    tyre_strategy: Dict[str, Any],
    pit_decision: Dict[str, Any]
) -> List[Dict[str, Any]]:
    """
    Score all dynamically generated strategies.
    """

    # ========================================================
    # BASE PHASE 3.6 SCORING
    # ========================================================

    base_scoring = (
        run_strategy_scoring(
            strategies
        )
    )


    base_strategies = base_scoring.get(
        "strategies",
        []
    )


    if not base_strategies:

        raise RuntimeError(
            "Base strategy scoring returned no strategies."
        )


    dynamic_strategies = []


    # ========================================================
    # ADD DYNAMIC CONTEXT
    # ========================================================

    for strategy in base_strategies:

        result = strategy.copy()


        context = (
            calculate_dynamic_context_score(

                strategy=result,

                race_situation=race_situation,

                tyre_strategy=tyre_strategy,

                pit_decision=pit_decision

            )
        )


        result.update(
            context
        )


        result[
            "base_overall_score"
        ] = result.get(
            "overall_score"
        )


        result[
            "dynamic_overall_score"
        ] = (
            calculate_dynamic_overall_score(

                base_score=result.get(
                    "overall_score",
                    0.0
                ),

                context_score=result.get(
                    "dynamic_context_score",
                    0.0
                )

            )
        )


        dynamic_strategies.append(
            result
        )


    # ========================================================
    # FINAL DYNAMIC RANKING
    # ========================================================

    dynamic_strategies.sort(

        key=lambda strategy:
            strategy[
                "dynamic_overall_score"
            ],

        reverse=True

    )


    for rank, strategy in enumerate(

        dynamic_strategies,

        start=1

    ):

        strategy[
            "dynamic_score_rank"
        ] = rank


    return dynamic_strategies


# ============================================================
# FIND BEST DYNAMIC STRATEGY
# ============================================================

def get_best_dynamic_strategy(
    strategies: List[Dict[str, Any]]
):
    """
    Return the highest dynamically scored strategy.
    """

    if not strategies:

        return None


    return max(

        strategies,

        key=lambda strategy:
            strategy[
                "dynamic_overall_score"
            ]

    )


# ============================================================
# COMPLETE PHASE 4.6 PIPELINE
# ============================================================

def run_dynamic_strategy_scoring(
    simulation_result: Dict[str, Any],
    race_state: Dict[str, Any],
    race_situation: Dict[str, Any],
    tyre_strategy: Dict[str, Any],
    pit_decision: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Run the complete Phase 4.6 dynamic scoring engine.
    """

    validate_dynamic_scoring_inputs(

        simulation_result=simulation_result,

        race_state=race_state,

        race_situation=race_situation,

        tyre_strategy=tyre_strategy,

        pit_decision=pit_decision

    )


    strategies = simulation_result.get(
        "strategies",
        []
    )


    scored_strategies = (
        score_dynamic_strategies(

            strategies=strategies,

            race_situation=race_situation,

            tyre_strategy=tyre_strategy,

            pit_decision=pit_decision

        )
    )


    best_strategy = (
        get_best_dynamic_strategy(
            scored_strategies
        )
    )


    return {

        "dynamic_scoring":
            True,

        "current_lap":
            race_state.get(
                "CurrentLap"
            ),

        "remaining_laps":
            race_state.get(
                "LapsRemaining"
            ),

        "position":
            race_state.get(
                "Position"
            ),

        "current_tyre":
            race_state.get(
                "TyreCompound"
            ),

        "race_situation":
            (

                race_situation.get(
                    "race_situation"
                )

                or

                race_situation.get(
                    "RaceSituation"
                )

            ),

        "pit_decision":
            (

                pit_decision.get(
                    "decision"
                )

                or

                pit_decision.get(
                    "action"
                )

            ),

        "strategy_count":
            len(
                scored_strategies
            ),

        "strategies":
            scored_strategies,

        "best_strategy":
            best_strategy,

        "best_dynamic_score":
            (

                best_strategy.get(
                    "dynamic_overall_score"
                )

                if best_strategy

                else None

            ),

        "best_strategy_rank":
            (

                best_strategy.get(
                    "dynamic_score_rank"
                )

                if best_strategy

                else None

            )

    }


# ============================================================
# DISPLAY
# ============================================================

def display_dynamic_strategy_scoring(
    result: Dict[str, Any]
) -> None:
    """
    Display Phase 4.6 scoring results.
    """

    print(
        "\n" + "=" * 72
    )

    print(
        "PHASE 4.6 — DYNAMIC STRATEGY SCORING"
    )

    print(
        "=" * 72
    )


    print(
        f"Current Lap: "
        f"{result.get('current_lap')}"
    )


    print(
        f"Remaining Laps: "
        f"{result.get('remaining_laps')}"
    )


    print(
        f"Position: P"
        f"{result.get('position')}"
    )


    print(
        f"Current Tyre: "
        f"{result.get('current_tyre')}"
    )


    print(
        f"Race Situation: "
        f"{result.get('race_situation')}"
    )


    print(
        f"Pit Decision: "
        f"{result.get('pit_decision')}"
    )


    print(
        "-" * 72
    )

    print(
        "DYNAMIC STRATEGY SCORES"
    )

    print(
        "-" * 72
    )


    for strategy in result.get(
        "strategies",
        []
    ):

        print(
            f"\nRank "
            f"{strategy.get('dynamic_score_rank')} "
            f"| "
            f"{strategy.get('tyre_plan')}"
        )


        print(
            f"Base Score: "
            f"{strategy.get('base_overall_score'):.2f}"
        )


        print(
            f"Decision Alignment: "
            f"{strategy.get('decision_alignment_score'):.2f}"
        )


        print(
            f"Tyre Alignment: "
            f"{strategy.get('tyre_alignment_score'):.2f}"
        )


        print(
            f"Race Situation: "
            f"{strategy.get('race_situation_score'):.2f}"
        )


        print(
            f"Dynamic Context: "
            f"{strategy.get('dynamic_context_score'):.2f}"
        )


        print(
            f"Dynamic Overall Score: "
            f"{strategy.get('dynamic_overall_score'):.2f}"
        )


    print(
        "-" * 72
    )


    best = result.get(
        "best_strategy"
    )


    if best:

        print(
            f"Best Strategy: "
            f"{best.get('tyre_plan')}"
        )


        print(
            f"Best Dynamic Score: "
            f"{best.get('dynamic_overall_score'):.2f}"
        )


        print(
            f"Dynamic Rank: "
            f"{best.get('dynamic_score_rank')}"
        )


    print(
        "=" * 72
    )