"""
V5 SPRINT 6 - STEP 5
FINAL MULTI-DRIVER STRATEGY INTEGRATION

This module combines the full-grid strategy analysis and
grid-level comparison into one final multi-driver strategy
output.

It provides:

- Complete grid strategy overview
- PIT NOW drivers
- STAY OUT drivers
- DATA UNAVAILABLE drivers
- High-confidence decisions
- Low-confidence decisions
- Pit probability ranking
- Pit opportunities
- Strategy conflicts
- Undercut opportunities
- Overcut opportunities
- Strategic priority ranking

This is the final integration layer of Sprint 6.
"""

from typing import Dict, List, Any


# ============================================================
# CONSTANTS
# ============================================================

PIT_NOW = "PIT NOW"

STAY_OUT = "STAY OUT"

DATA_UNAVAILABLE = "DATA UNAVAILABLE"

HIGH = "HIGH"

MEDIUM = "MEDIUM"

LOW = "LOW"


# ============================================================
# SAFE NUMERIC CONVERSION
# ============================================================

def _safe_float(
    value: Any
):
    """
    Safely convert a value to float.

    Returns
    -------
    float or None
    """

    if value is None:

        return None

    try:

        return float(
            value
        )

    except (
        TypeError,
        ValueError
    ):

        return None


# ============================================================
# VALIDATE GRID COMPARISON
# ============================================================

def validate_grid_comparison(
    comparison: Dict[str, Any]
) -> None:
    """
    Validate the output generated by
    grid_comparison.py.
    """

    if not isinstance(
        comparison,
        dict
    ):

        raise TypeError(
            "comparison must be a dictionary."
        )


    required_fields = [

        "total_drivers",

        "successful_drivers",

        "data_unavailable_drivers",

        "strategy_groups",

        "high_confidence_drivers",

        "low_confidence_drivers",

        "pit_probability_ranking",

        "pit_opportunities",

        "strategy_conflicts",

        "undercut_opportunities",

        "overcut_opportunities",

        "driver_results"

    ]


    missing_fields = [

        field

        for field in required_fields

        if field not in comparison

    ]


    if missing_fields:

        raise ValueError(

            "Missing required grid comparison fields: "

            + ", ".join(
                missing_fields
            )

        )


# ============================================================
# GET DRIVER STRATEGY PRIORITY
# ============================================================

def calculate_strategy_priority(
    driver_result: Dict[str, Any]
) -> float:
    """
    Calculate a strategic priority score for a driver.

    Higher score means the driver requires more immediate
    strategic attention.

    Factors:

    - Pit probability
    - Confidence
    - Final decision
    - Tyre age
    """

    if not isinstance(
        driver_result,
        dict
    ):

        return 0.0


    if driver_result.get(
        "final_decision"
    ) == DATA_UNAVAILABLE:

        return 0.0


    score = 0.0


    # --------------------------------------------------------
    # PIT PROBABILITY
    # --------------------------------------------------------

    pit_probability = _safe_float(

        driver_result.get(
            "pit_probability"
        )

    )


    if pit_probability is not None:

        score += (

            pit_probability
            * 100.0

        )


    # --------------------------------------------------------
    # CONFIDENCE
    # --------------------------------------------------------

    confidence = driver_result.get(
        "confidence"
    )


    if confidence == HIGH:

        score += 20.0

    elif confidence == MEDIUM:

        score += 10.0

    elif confidence == LOW:

        score += 5.0


    # --------------------------------------------------------
    # PIT DECISION
    # --------------------------------------------------------

    if driver_result.get(
        "final_decision"
    ) == PIT_NOW:

        score += 20.0


    # --------------------------------------------------------
    # TYRE AGE
    # --------------------------------------------------------

    tyre_life = _safe_float(

        driver_result.get(
            "tyre_life"
        )

    )


    if tyre_life is not None:

        score += min(

            tyre_life,

            20.0

        )


    return round(

        score,

        4

    )


# ============================================================
# RANK STRATEGIC PRIORITIES
# ============================================================

def rank_strategic_priorities(
    driver_results: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Rank all successfully analyzed drivers by
    strategic priority.
    """

    if not isinstance(
        driver_results,
        list
    ):

        raise TypeError(
            "driver_results must be a list."
        )


    ranked = []


    for result in driver_results:

        if not isinstance(
            result,
            dict
        ):

            continue


        if result.get(
            "final_decision"
        ) == DATA_UNAVAILABLE:

            continue


        driver = result.get(
            "driver"
        )


        if not driver:

            continue


        priority_score = (

            calculate_strategy_priority(

                result

            )

        )


        ranked.append(

            {

                "driver":
                    driver,

                "position":
                    result.get(
                        "position"
                    ),

                "tyre_compound":
                    result.get(
                        "tyre_compound"
                    ),

                "tyre_life":
                    result.get(
                        "tyre_life"
                    ),

                "pit_probability":
                    result.get(
                        "pit_probability"
                    ),

                "final_decision":
                    result.get(
                        "final_decision"
                    ),

                "confidence":
                    result.get(
                        "confidence"
                    ),

                "strategy_priority":
                    priority_score

            }

        )


    ranked.sort(

        key=lambda item:

            item[
                "strategy_priority"
            ],

        reverse=True

    )


    return ranked


# ============================================================
# IDENTIFY PRIMARY STRATEGIC FOCUS
# ============================================================

def identify_primary_strategic_focus(
    comparison: Dict[str, Any],
    priority_ranking: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Identify the most important strategic focus
    across the full grid.
    """

    strategy_groups = comparison.get(

        "strategy_groups",

        {}

    )


    pit_drivers = strategy_groups.get(

        "pit_drivers",

        []

    )


    stay_out_drivers = strategy_groups.get(

        "stay_out_drivers",

        []

    )


    unavailable_drivers = strategy_groups.get(

        "data_unavailable_drivers",

        []

    )


    conflicts = comparison.get(

        "strategy_conflicts",

        []

    )


    pit_opportunities = comparison.get(

        "pit_opportunities",

        []

    )


    undercut_opportunities = comparison.get(

        "undercut_opportunities",

        []

    )


    overcut_opportunities = comparison.get(

        "overcut_opportunities",

        []

    )


    # --------------------------------------------------------
    # DEFAULT FOCUS
    # --------------------------------------------------------

    focus = {

        "primary_focus":
            "MONITOR",

        "priority_driver":
            None,

        "reason":
            "No immediate strategic priority detected.",

        "pit_drivers":
            pit_drivers,

        "stay_out_drivers":
            stay_out_drivers,

        "data_unavailable_drivers":
            unavailable_drivers,

        "strategy_conflicts":
            len(
                conflicts
            ),

        "pit_opportunities":
            len(
                pit_opportunities
            ),

        "undercut_opportunities":
            len(
                undercut_opportunities
            ),

        "overcut_opportunities":
            len(
                overcut_opportunities
            )

    }


    # --------------------------------------------------------
    # PRIORITY DRIVER
    # --------------------------------------------------------

    if priority_ranking:

        top_driver = priority_ranking[0]


        focus[
            "priority_driver"
        ] = top_driver.get(
            "driver"
        )


    # --------------------------------------------------------
    # PIT PRIORITY
    # --------------------------------------------------------

    if pit_drivers:

        focus[
            "primary_focus"
        ] = PIT_NOW


        focus[
            "reason"
        ] = (

            "One or more drivers have been "
            "identified for an immediate pit "
            "strategy recommendation."

        )


    # --------------------------------------------------------
    # STRATEGY CONFLICT
    # --------------------------------------------------------

    elif conflicts:

        focus[
            "primary_focus"
        ] = "REVIEW CONFLICT"


        focus[
            "reason"
        ] = (

            "ML and simulation strategy signals "
            "conflict for one or more drivers. "
            "Additional strategic review is recommended."

        )


    # --------------------------------------------------------
    # UNDERCUT
    # --------------------------------------------------------

    elif undercut_opportunities:

        focus[
            "primary_focus"
        ] = "UNDERCUT"


        focus[
            "reason"
        ] = (

            "Potential undercut opportunities "
            "have been identified across the grid."

        )


    # --------------------------------------------------------
    # OVERCUT
    # --------------------------------------------------------

    elif overcut_opportunities:

        focus[
            "primary_focus"
        ] = "OVERCUT"


        focus[
            "reason"
        ] = (

            "Potential overcut opportunities "
            "have been identified across the grid."

        )


    # --------------------------------------------------------
    # MONITOR
    # --------------------------------------------------------

    else:

        focus[
            "primary_focus"
        ] = "MONITOR"


        focus[
            "reason"
        ] = (

            "No immediate pit or strategic conflict "
            "requires intervention. Continue monitoring "
            "the full grid."

        )


    return focus


# ============================================================
# BUILD FINAL MULTI-DRIVER STRATEGY
# ============================================================

def build_multi_driver_strategy(
    comparison: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Build the final Sprint 6 multi-driver strategy output.

    Parameters
    ----------
    comparison : dict
        Output generated by build_grid_strategy_comparison().

    Returns
    -------
    dict
        Complete multi-driver strategy analysis.
    """

    # --------------------------------------------------------
    # VALIDATE INPUT
    # --------------------------------------------------------

    validate_grid_comparison(

        comparison

    )


    # --------------------------------------------------------
    # EXTRACT DRIVER RESULTS
    # --------------------------------------------------------

    driver_results = comparison.get(

        "driver_results",

        []

    )


    # --------------------------------------------------------
    # RANK STRATEGIC PRIORITIES
    # --------------------------------------------------------

    priority_ranking = (

        rank_strategic_priorities(

            driver_results

        )

    )


    # --------------------------------------------------------
    # IDENTIFY PRIMARY FOCUS
    # --------------------------------------------------------

    primary_focus = (

        identify_primary_strategic_focus(

            comparison,

            priority_ranking

        )

    )


    # --------------------------------------------------------
    # BUILD FINAL OUTPUT
    # --------------------------------------------------------

    return {

        "total_drivers":
            comparison[
                "total_drivers"
            ],

        "successful_drivers":
            comparison[
                "successful_drivers"
            ],

        "data_unavailable_drivers":
            comparison[
                "data_unavailable_drivers"
            ],

        "strategy_groups":
            comparison[
                "strategy_groups"
            ],

        "high_confidence_drivers":
            comparison[
                "high_confidence_drivers"
            ],

        "low_confidence_drivers":
            comparison[
                "low_confidence_drivers"
            ],

        "pit_probability_ranking":
            comparison[
                "pit_probability_ranking"
            ],

        "pit_opportunities":
            comparison[
                "pit_opportunities"
            ],

        "strategy_conflicts":
            comparison[
                "strategy_conflicts"
            ],

        "undercut_opportunities":
            comparison[
                "undercut_opportunities"
            ],

        "overcut_opportunities":
            comparison[
                "overcut_opportunities"
            ],

        "strategic_priority_ranking":
            priority_ranking,

        "primary_strategic_focus":
            primary_focus,

        "driver_results":
            driver_results

    }


# ============================================================
# PRINT FINAL MULTI-DRIVER STRATEGY
# ============================================================

def print_multi_driver_strategy(
    strategy: Dict[str, Any]
) -> None:
    """
    Print the final multi-driver strategy output.
    """

    if not isinstance(
        strategy,
        dict
    ):

        raise TypeError(
            "strategy must be a dictionary."
        )


    print(

        "\n"
        + "=" * 110

    )


    print(

        "V5 FINAL MULTI-DRIVER STRATEGY"

    )


    print(

        "=" * 110

    )


    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print(

        f"Total Drivers: "
        f"{strategy.get('total_drivers', 0)}"

    )


    print(

        f"Successfully Analyzed: "
        f"{strategy.get('successful_drivers', 0)}"

    )


    print(

        f"Data Unavailable: "
        f"{strategy.get('data_unavailable_drivers', 0)}"

    )


    # --------------------------------------------------------
    # PRIMARY FOCUS
    # --------------------------------------------------------

    focus = strategy.get(

        "primary_strategic_focus",

        {}

    )


    print(

        "\n"
        + "-" * 110

    )


    print(

        "PRIMARY STRATEGIC FOCUS"

    )


    print(

        "-" * 110

    )


    print(

        f"Focus: "
        f"{focus.get('primary_focus')}"

    )


    print(

        f"Priority Driver: "
        f"{focus.get('priority_driver')}"

    )


    print(

        f"Reason: "
        f"{focus.get('reason')}"

    )


    # --------------------------------------------------------
    # STRATEGY GROUPS
    # --------------------------------------------------------

    groups = strategy.get(

        "strategy_groups",

        {}

    )


    print(

        "\n"
        + "-" * 110

    )


    print(

        "STRATEGY GROUPS"

    )


    print(

        "-" * 110

    )


    print(

        "PIT NOW:"

    )


    print(

        ", ".join(

            groups.get(

                "pit_drivers",

                []

            )

        )

        or

        "None"

    )


    print(

        "\nSTAY OUT:"

    )


    print(

        ", ".join(

            groups.get(

                "stay_out_drivers",

                []

            )

        )

        or

        "None"

    )


    print(

        "\nDATA UNAVAILABLE:"

    )


    print(

        ", ".join(

            groups.get(

                "data_unavailable_drivers",

                []

            )

        )

        or

        "None"

    )


    # --------------------------------------------------------
    # STRATEGIC PRIORITY RANKING
    # --------------------------------------------------------

    print(

        "\n"
        + "-" * 110

    )


    print(

        "STRATEGIC PRIORITY RANKING"

    )


    print(

        "-" * 110

    )


    ranking = strategy.get(

        "strategic_priority_ranking",

        []

    )


    if not ranking:

        print(

            "No strategic priorities available."

        )


    else:

        print(

            f"{'Rank':<6}"

            f"{'Driver':<10}"

            f"{'Position':<10}"

            f"{'Tyre':<15}"

            f"{'Pit Prob.':<15}"

            f"{'Decision':<15}"

            f"{'Confidence':<12}"

            f"{'Priority':<10}"

        )


        print(

            "-" * 100

        )


        for index, item in enumerate(

            ranking,

            start=1

        ):

            pit_probability = item.get(

                "pit_probability"

            )


            if pit_probability is None:

                pit_probability_text = "N/A"

            else:

                pit_probability_text = (

                    f"{pit_probability:.4f}%"

                )


            print(

                f"{index:<6}"

                f"{str(item.get('driver')):<10}"

                f"{str(item.get('position')):<10}"

                f"{str(item.get('tyre_compound')):<15}"

                f"{pit_probability_text:<15}"

                f"{str(item.get('final_decision')):<15}"

                f"{str(item.get('confidence')):<12}"

                f"{str(item.get('strategy_priority')):<10}"

            )


    # --------------------------------------------------------
    # PIT OPPORTUNITIES
    # --------------------------------------------------------

    print(

        "\n"
        + "-" * 110

    )


    print(

        "PIT OPPORTUNITIES"

    )


    print(

        "-" * 110

    )


    pit_opportunities = strategy.get(

        "pit_opportunities",

        []

    )


    if not pit_opportunities:

        print(

            "None detected."

        )

    else:

        for item in pit_opportunities:

            print(

                f"{item.get('driver')} | "

                f"Pit Probability: "
                f"{item.get('pit_probability')}% | "

                f"Tyre: "
                f"{item.get('tyre_compound')} | "

                f"Tyre Age: "
                f"{item.get('tyre_life')}"

            )


    # --------------------------------------------------------
    # STRATEGY CONFLICTS
    # --------------------------------------------------------

    print(

        "\n"
        + "-" * 110

    )


    print(

        "STRATEGY CONFLICTS"

    )


    print(

        "-" * 110

    )


    conflicts = strategy.get(

        "strategy_conflicts",

        []

    )


    if not conflicts:

        print(

            "None detected."

        )

    else:

        for conflict in conflicts:

            print(

                f"{conflict.get('driver')} | "

                f"ML: "
                f"{conflict.get('ml_recommendation')} | "

                f"Simulator: "
                f"{conflict.get('simulator_recommendation')} | "

                f"Final: "
                f"{conflict.get('final_decision')}"

            )


    # --------------------------------------------------------
    # UNDERCUT
    # --------------------------------------------------------

    print(

        "\n"
        + "-" * 110

    )


    print(

        "UNDERCUT OPPORTUNITIES"

    )


    print(

        "-" * 110

    )


    undercuts = strategy.get(

        "undercut_opportunities",

        []

    )


    if not undercuts:

        print(

            "None detected."

        )

    else:

        for item in undercuts:

            print(

                f"{item.get('driver')} | "

                f"Score: "
                f"{item.get('score')}"

            )


    # --------------------------------------------------------
    # OVERCUT
    # --------------------------------------------------------

    print(

        "\n"
        + "-" * 110

    )


    print(

        "OVERCUT OPPORTUNITIES"

    )


    print(

        "-" * 110

    )


    overcuts = strategy.get(

        "overcut_opportunities",

        []

    )


    if not overcuts:

        print(

            "None detected."

        )

    else:

        for item in overcuts:

            print(

                f"{item.get('driver')} | "

                f"Score: "
                f"{item.get('score')}"

            )


    print(

        "\n"
        + "=" * 110

    )


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    print(

        "=" * 110

    )


    print(

        "V5 SPRINT 6 - STEP 5"

    )


    print(

        "FINAL MULTI-DRIVER STRATEGY INTEGRATION"

    )


    print(

        "=" * 110

    )


    # --------------------------------------------------------
    # SAMPLE GRID COMPARISON
    # --------------------------------------------------------

    sample_comparison = {

        "total_drivers":
            4,

        "successful_drivers":
            3,

        "data_unavailable_drivers":
            1,

        "strategy_groups": {

            "pit_drivers":
                [
                    "VER"
                ],

            "stay_out_drivers":
                [
                    "NOR",
                    "LEC"
                ],

            "data_unavailable_drivers":
                [
                    "ANT"
                ],

            "other_drivers":
                []

        },

        "high_confidence_drivers":
            [
                "VER",
                "NOR"
            ],

        "low_confidence_drivers":
            [
                "LEC"
            ],

        "pit_probability_ranking": [],

        "pit_opportunities": [],

        "strategy_conflicts": [],

        "undercut_opportunities": [],

        "overcut_opportunities": [],

        "driver_results": [

            {

                "driver":
                    "VER",

                "position":
                    1,

                "tyre_compound":
                    "MEDIUM",

                "tyre_life":
                    15,

                "pit_probability":
                    0.35,

                "final_decision":
                    "PIT NOW",

                "confidence":
                    "HIGH"

            },

            {

                "driver":
                    "NOR",

                "position":
                    2,

                "tyre_compound":
                    "MEDIUM",

                "tyre_life":
                    8,

                "pit_probability":
                    0.12,

                "final_decision":
                    "STAY OUT",

                "confidence":
                    "HIGH"

            },

            {

                "driver":
                    "LEC",

                "position":
                    3,

                "tyre_compound":
                    "SOFT",

                "tyre_life":
                    14,

                "pit_probability":
                    0.28,

                "final_decision":
                    "STAY OUT",

                "confidence":
                    "LOW"

            },

            {

                "driver":
                    "ANT",

                "position":
                    16,

                "tyre_compound":
                    "INTERMEDIATE",

                "tyre_life":
                    3,

                "pit_probability":
                    None,

                "final_decision":
                    "DATA UNAVAILABLE",

                "confidence":
                    None

            }

        ]

    }


    # --------------------------------------------------------
    # BUILD FINAL STRATEGY
    # --------------------------------------------------------

    final_strategy = (

        build_multi_driver_strategy(

            sample_comparison

        )

    )


    # --------------------------------------------------------
    # DISPLAY
    # --------------------------------------------------------

    print_multi_driver_strategy(

        final_strategy

    )


    print(

        "\n"
        "✅ STEP 6.5 SAMPLE TEST COMPLETED"

    )