"""
strategy_scoring.py

PHASE 3.6 — STRATEGY SCORING

Purpose
-------
Convert the projected strategies generated by Phase 3.5 into
a unified strategy score.

The scoring system considers:

    Pace Performance
    Tyre Performance
    Pit Cost
    Traffic Impact
    Track Position
    Degradation
    Risk

The final score is normalized to 0–100.

Higher score = better strategic option.

This module does NOT:
    - simulate strategies
    - make the final AI recommendation
    - expose an API
    - handle frontend logic

Those responsibilities belong to other Phase 3 modules.
"""

from typing import Dict, Any, List


# ============================================================
# SCORE WEIGHTS
# ============================================================

PACE_WEIGHT = 0.25

TYRE_WEIGHT = 0.15

PIT_WEIGHT = 0.15

TRAFFIC_WEIGHT = 0.10

POSITION_WEIGHT = 0.10

DEGRADATION_WEIGHT = 0.10

RISK_WEIGHT = 0.15


# ============================================================
# INPUT VALIDATION
# ============================================================

def validate_strategies(
    strategies: List[Dict[str, Any]]
) -> None:
    """
    Validate the strategy list received from Phase 3.5.
    """

    if not strategies:

        raise ValueError(
            "Strategy list cannot be empty."
        )

    required_fields = [

        "strategy",

        "projected_total_time",

        "pit_loss",

        "degradation_impact",

        "stops"

    ]

    for strategy in strategies:

        for field in required_fields:

            if field not in strategy:

                raise ValueError(

                    f"Missing required strategy "
                    f"field: {field}"

                )


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_lower_is_better(
    value: float,
    minimum: float,
    maximum: float
) -> float:
    """
    Convert a lower-is-better metric into a 0–100 score.

    Lower value -> higher score.
    """

    if maximum == minimum:

        return 100.0

    score = (

        (maximum - value)

        /

        (maximum - minimum)

    ) * 100

    return round(

        max(
            0.0,
            min(
                100.0,
                score
            )
        ),

        2

    )


def normalize_higher_is_better(
    value: float,
    minimum: float,
    maximum: float
) -> float:
    """
    Convert a higher-is-better metric into a 0–100 score.
    """

    if maximum == minimum:

        return 100.0

    score = (

        (value - minimum)

        /

        (maximum - minimum)

    ) * 100

    return round(

        max(
            0.0,
            min(
                100.0,
                score
            )
        ),

        2

    )


# ============================================================
# PACE SCORE
# ============================================================

def calculate_pace_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate pace scores.

    Lower projected total time = better pace score.
    """

    times = [

        strategy[
            "projected_total_time"
        ]

        for strategy in strategies

    ]

    minimum = min(times)

    maximum = max(times)

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        scores[index] = normalize_lower_is_better(

            strategy[
                "projected_total_time"
            ],

            minimum,

            maximum

        )

    return scores


# ============================================================
# TYRE PERFORMANCE SCORE
# ============================================================

def calculate_tyre_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate tyre-performance scores.

    Lower degradation impact receives a higher score.
    """

    degradation_values = [

        strategy[
            "degradation_impact"
        ]

        for strategy in strategies

    ]

    minimum = min(
        degradation_values
    )

    maximum = max(
        degradation_values
    )

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        scores[index] = normalize_lower_is_better(

            strategy[
                "degradation_impact"
            ],

            minimum,

            maximum

        )

    return scores


# ============================================================
# PIT COST SCORE
# ============================================================

def calculate_pit_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate pit-cost scores.

    Strategies without a pit receive the
    maximum pit score.

    Lower pit loss = better score.
    """

    pit_losses = [

        strategy[
            "pit_loss"
        ]

        for strategy in strategies

    ]

    minimum = min(
        pit_losses
    )

    maximum = max(
        pit_losses
    )

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        scores[index] = normalize_lower_is_better(

            strategy[
                "pit_loss"
            ],

            minimum,

            maximum

        )

    return scores


# ============================================================
# TRAFFIC SCORE
# ============================================================

def calculate_traffic_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate traffic scores.

    The current simulator does not yet contain
    detailed traffic modelling.

    Therefore:

        STAY_OUT -> 100
        PIT      -> 80

    This gives a modest penalty to pit strategies
    while keeping traffic modelling isolated for
    future improvements.
    """

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        if strategy[
            "strategy"
        ] == "STAY_OUT":

            scores[index] = 100.0

        else:

            scores[index] = 80.0

    return scores


# ============================================================
# TRACK POSITION SCORE
# ============================================================

def calculate_position_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate track-position scores.

    Staying out preserves current track position.

    A pit stop introduces the possibility of losing
    track position.

    This is intentionally conservative until detailed
    traffic modelling is added.
    """

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        if strategy[
            "strategy"
        ] == "STAY_OUT":

            scores[index] = 100.0

        else:

            scores[index] = 85.0

    return scores


# ============================================================
# DEGRADATION SCORE
# ============================================================

def calculate_degradation_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate degradation scores.

    Lower degradation impact receives a higher score.
    """

    degradation_values = [

        strategy[
            "degradation_impact"
        ]

        for strategy in strategies

    ]

    minimum = min(
        degradation_values
    )

    maximum = max(
        degradation_values
    )

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        scores[index] = normalize_lower_is_better(

            strategy[
                "degradation_impact"
            ],

            minimum,

            maximum

        )

    return scores


# ============================================================
# RISK SCORE
# ============================================================

def calculate_risk_scores(
    strategies: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate strategic risk scores.

    Fewer pit stops generally means lower operational risk.

    STAY_OUT receives the highest baseline score.

    One-stop strategies receive a moderate score.
    """

    scores = {}

    for index, strategy in enumerate(
        strategies
    ):

        stops = strategy[
            "stops"
        ]

        if stops == 0:

            scores[index] = 95.0

        elif stops == 1:

            scores[index] = 85.0

        else:

            scores[index] = 70.0

    return scores


# ============================================================
# CALCULATE OVERALL SCORE
# ============================================================

def calculate_overall_score(
    pace_score: float,
    tyre_score: float,
    pit_score: float,
    traffic_score: float,
    position_score: float,
    degradation_score: float,
    risk_score: float
) -> float:
    """
    Calculate the weighted unified strategy score.
    """

    score = (

        pace_score
        * PACE_WEIGHT

        +

        tyre_score
        * TYRE_WEIGHT

        +

        pit_score
        * PIT_WEIGHT

        +

        traffic_score
        * TRAFFIC_WEIGHT

        +

        position_score
        * POSITION_WEIGHT

        +

        degradation_score
        * DEGRADATION_WEIGHT

        +

        risk_score
        * RISK_WEIGHT

    )

    return round(

        score,

        2

    )


# ============================================================
# SCORE ALL STRATEGIES
# ============================================================

def score_strategies(
    strategies: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """
    Score every strategy generated by Phase 3.5.
    """

    validate_strategies(
        strategies
    )

    pace_scores = (
        calculate_pace_scores(
            strategies
        )
    )

    tyre_scores = (
        calculate_tyre_scores(
            strategies
        )
    )

    pit_scores = (
        calculate_pit_scores(
            strategies
        )
    )

    traffic_scores = (
        calculate_traffic_scores(
            strategies
        )
    )

    position_scores = (
        calculate_position_scores(
            strategies
        )
    )

    degradation_scores = (
        calculate_degradation_scores(
            strategies
        )
    )

    risk_scores = (
        calculate_risk_scores(
            strategies
        )
    )

    scored_strategies = []

    for index, strategy in enumerate(
        strategies
    ):

        result = strategy.copy()

        result[
            "pace_score"
        ] = pace_scores[index]

        result[
            "tyre_score"
        ] = tyre_scores[index]

        result[
            "pit_score"
        ] = pit_scores[index]

        result[
            "traffic_score"
        ] = traffic_scores[index]

        result[
            "position_score"
        ] = position_scores[index]

        result[
            "degradation_score"
        ] = degradation_scores[index]

        result[
            "risk_score"
        ] = risk_scores[index]

        result[
            "overall_score"
        ] = calculate_overall_score(

            pace_score=pace_scores[index],

            tyre_score=tyre_scores[index],

            pit_score=pit_scores[index],

            traffic_score=traffic_scores[index],

            position_score=position_scores[index],

            degradation_score=(
                degradation_scores[index]
            ),

            risk_score=risk_scores[index]

        )

        scored_strategies.append(
            result
        )

    # --------------------------------------------------------
    # RANK BY OVERALL SCORE
    # --------------------------------------------------------

    scored_strategies.sort(

        key=lambda strategy:
        strategy[
            "overall_score"
        ],

        reverse=True

    )

    for rank, strategy in enumerate(

        scored_strategies,

        start=1

    ):

        strategy[
            "score_rank"
        ] = rank

    return scored_strategies


# ============================================================
# GET BEST SCORED STRATEGY
# ============================================================

def get_best_scored_strategy(
    strategies: List[Dict[str, Any]]
) -> Dict[str, Any] | None:
    """
    Return the highest-scoring strategy.
    """

    if not strategies:

        return None

    return max(

        strategies,

        key=lambda strategy:
        strategy[
            "overall_score"
        ]

    )


# ============================================================
# COMPLETE STRATEGY SCORING
# ============================================================

def run_strategy_scoring(
    strategies: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Run the complete Phase 3.6 scoring pipeline.
    """

    scored_strategies = score_strategies(
        strategies
    )

    best_strategy = (
        get_best_scored_strategy(
            scored_strategies
        )
    )

    return {

        "strategy_count":
            len(scored_strategies),

        "strategies":
            scored_strategies,

        "best_strategy":
            best_strategy,

        "best_score":
            (
                best_strategy[
                    "overall_score"
                ]

                if best_strategy

                else None
            )

    }


# ============================================================
# DISPLAY STRATEGY SCORES
# ============================================================

def display_strategy_scores(
    result: Dict[str, Any]
) -> None:
    """
    Display complete strategy scoring results.
    """

    print(
        "\n" + "=" * 60
    )

    print(
        "STRATEGY SCORING"
    )

    print(
        "=" * 60
    )

    strategies = result.get(
        "strategies",
        []
    )

    if not strategies:

        print(
            "No scored strategies available."
        )

        return

    for strategy in strategies:

        print(
            f"\nRank: "
            f"{strategy['score_rank']}"
        )

        print(
            f"Strategy: "
            f"{strategy['strategy']}"
        )

        print(
            f"Tyre Plan: "
            f"{strategy['tyre_plan']}"
        )

        print(
            "-" * 40
        )

        print(
            f"Pace Score: "
            f"{strategy['pace_score']:.2f}"
        )

        print(
            f"Tyre Score: "
            f"{strategy['tyre_score']:.2f}"
        )

        print(
            f"Pit Score: "
            f"{strategy['pit_score']:.2f}"
        )

        print(
            f"Traffic Score: "
            f"{strategy['traffic_score']:.2f}"
        )

        print(
            f"Position Score: "
            f"{strategy['position_score']:.2f}"
        )

        print(
            f"Degradation Score: "
            f"{strategy['degradation_score']:.2f}"
        )

        print(
            f"Risk Score: "
            f"{strategy['risk_score']:.2f}"
        )

        print(
            "-" * 40
        )

        print(
            f"Overall Score: "
            f"{strategy['overall_score']:.2f}"
        )

    # --------------------------------------------------------
    # BEST STRATEGY
    # --------------------------------------------------------

    best = result.get(
        "best_strategy"
    )

    print(
        "\n" + "=" * 60
    )

    print(
        "BEST SCORED STRATEGY"
    )

    print(
        "=" * 60
    )

    if best:

        print(
            f"Strategy: "
            f"{best['strategy']}"
        )

        print(
            f"Tyre Plan: "
            f"{best['tyre_plan']}"
        )

        print(
            f"Overall Score: "
            f"{best['overall_score']:.2f}"
        )

        print(
            f"Score Rank: "
            f"{best['score_rank']}"
        )

    print(
        "=" * 60
    )


# ============================================================
# PHASE 3.6 TEST
# ============================================================

if __name__ == "__main__":

    from src.strategy.strategy_simulation import (
        run_strategy_simulation
    )

    print(
        "\n" + "=" * 60
    )

    print(
        "F1 AI STRATEGIST"
    )

    print(
        "PHASE 3.6 — STRATEGY SCORING"
    )

    print(
        "=" * 60
    )

    # --------------------------------------------------------
    # TEST CONFIGURATION
    # --------------------------------------------------------

    BASE_LAP_TIME = 96.8

    CURRENT_TYRE = "HARD"

    TYRE_AGE = 22

    REMAINING_LAPS = 22

    PIT_LOSS = 22.0

    # --------------------------------------------------------
    # PHASE 3.5
    # --------------------------------------------------------

    print(
        "\n[1/3] Loading simulated strategies..."
    )

    simulation_result = (
        run_strategy_simulation(

            base_lap_time=BASE_LAP_TIME,

            current_tyre=CURRENT_TYRE,

            tyre_age=TYRE_AGE,

            remaining_laps=REMAINING_LAPS,

            pit_loss=PIT_LOSS

        )
    )

    strategies = simulation_result[
        "strategies"
    ]

    print(
        f"Loaded "
        f"{len(strategies)} "
        f"candidate strategies."
    )

    # --------------------------------------------------------
    # PHASE 3.6
    # --------------------------------------------------------

    print(
        "\n[2/3] Calculating strategy scores..."
    )

    scoring_result = run_strategy_scoring(
        strategies
    )

    print(
        "Strategy scoring completed."
    )

    # --------------------------------------------------------
    # DISPLAY
    # --------------------------------------------------------

    print(
        "\n[3/3] Ranking strategies..."
    )

    display_strategy_scores(
        scoring_result
    )

    # --------------------------------------------------------
    # VALIDATION
    # --------------------------------------------------------

    scored = scoring_result[
        "strategies"
    ]

    assert len(scored) == 4, (
        "Expected four scored strategies."
    )

    assert all(

        "overall_score" in strategy

        for strategy in scored

    ), (
        "Overall score missing."
    )

    assert all(

        0 <= strategy[
            "overall_score"
        ] <= 100

        for strategy in scored

    ), (
        "Overall score must be between 0 and 100."
    )

    assert all(

        "pace_score" in strategy

        and "tyre_score" in strategy

        and "pit_score" in strategy

        and "traffic_score" in strategy

        and "position_score" in strategy

        and "degradation_score" in strategy

        and "risk_score" in strategy

        for strategy in scored

    ), (
        "One or more component scores are missing."
    )

    assert (
        scored[0]["score_rank"] == 1
    ), (
        "Highest scoring strategy is not ranked first."
    )

    assert (
        scoring_result[
            "best_strategy"
        ]
        is not None
    ), (
        "Best scored strategy was not generated."
    )

    print(
        "\n" + "=" * 60
    )

    print(
        "✅ PHASE 3.6 STRATEGY SCORING TEST PASSED"
    )

    print(
        "=" * 60
    )