"""
strategy_pipeline.py

V5 Sprint 2 - End-to-End Strategy Pipeline

Purpose:
--------
Connect the complete F1 AI Strategist pipeline.

Pipeline:

    FastF1 Session
          ↓
    Race State
          ↓
    ML Feature Engineering
          ↓
    XGBoost Prediction
          ↓
    Strategy Simulation
          ↓
    Decision Engine
          ↓
    Final AI Strategy Decision

This module does NOT train the ML model.

It acts as the main orchestration layer for the
V5 AI Strategy Engine.
"""

from typing import Any, Dict

import pandas as pd

from src.data_loader import (
    load_session
)

from src.race_state import (
    build_race_state
)

from src.feature_engineering import (
    build_ml_features,
    validate_ml_features
)

from src.strategy.decision_engine import (
    get_strategy_decision
)


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_THRESHOLD = 50.0


# ============================================================
# BUILD STRATEGY INPUT
# ============================================================

def build_strategy_input(
    race_state: Dict[str, Any]
) -> pd.DataFrame:
    """
    Convert the structured race state into the exact
    ML feature format required by the trained model.

    Parameters
    ----------
    race_state : dict
        Structured race state generated by race_state.py.

    Returns
    -------
    pandas.DataFrame
        Validated single-row ML feature DataFrame.
    """

    if not isinstance(
        race_state,
        dict
    ):

        raise TypeError(
            "race_state must be a dictionary."
        )

    # --------------------------------------------------------
    # BUILD ML FEATURES
    # --------------------------------------------------------

    model_data = build_ml_features(
        race_state
    )

    # --------------------------------------------------------
    # VALIDATE ML FEATURES
    # --------------------------------------------------------

    validate_ml_features(
        model_data
    )

    return model_data


# ============================================================
# RUN STRATEGY PIPELINE
# ============================================================

def run_strategy_pipeline(
    season: int,
    grand_prix: str,
    driver: str,
    session_type: str = "R",
    threshold: float = DEFAULT_THRESHOLD
) -> Dict[str, Any]:
    """
    Run the complete V5 AI strategy pipeline.

    Pipeline:

        FastF1 Session
              ↓
        Race State
              ↓
        ML Features
              ↓
        XGBoost Prediction
              ↓
        Strategy Simulation
              ↓
        Decision Engine
              ↓
        Final Recommendation

    Parameters
    ----------
    season : int
        F1 season year.

    grand_prix : str
        Grand Prix name.

    driver : str
        Driver abbreviation.
        Example:
            VER
            HAM
            LEC

    session_type : str
        FastF1 session type.
        Default:
            R = Race

    threshold : float
        ML pit probability threshold.

    Returns
    -------
    dict
        Complete AI strategy result.
    """

    # ========================================================
    # VALIDATION
    # ========================================================

    if not isinstance(
        season,
        int
    ):

        raise TypeError(
            "season must be an integer."
        )

    if not grand_prix:

        raise ValueError(
            "grand_prix cannot be empty."
        )

    if not driver:

        raise ValueError(
            "driver cannot be empty."
        )

    if not session_type:

        raise ValueError(
            "session_type cannot be empty."
        )

    if not (
        0.0
        <= threshold
        <= 100.0
    ):

        raise ValueError(
            "threshold must be between 0 and 100."
        )

    driver = str(
        driver
    ).upper()

    # ========================================================
    # STEP 1 - LOAD FASTF1 SESSION
    # ========================================================

    print(
        "\n[1/5] Loading FastF1 session..."
    )

    session = load_session(

        season,

        grand_prix,

        session_type

    )

    if session is None:

        raise RuntimeError(

            "Failed to load FastF1 session."

        )

    print(
        "FastF1 session loaded successfully."
    )

    # ========================================================
    # STEP 2 - BUILD RACE STATE
    # ========================================================

    print(
        "\n[2/5] Building race state..."
    )

    race_state = build_race_state(

        session,

        driver

    )

    if not race_state:

        raise RuntimeError(

            "Race state generation returned empty data."

        )

    print(
        "Race state generated successfully."
    )

    # ========================================================
    # STEP 3 - BUILD ML FEATURES
    # ========================================================

    print(
        "\n[3/5] Building ML features..."
    )

    model_data = build_strategy_input(

        race_state

    )

    print(
        "ML features generated and validated successfully."
    )

    # ========================================================
    # STEP 4 - RUN DECISION ENGINE
    # ========================================================

    print(
        "\n[4/5] Running AI decision engine..."
    )

    # --------------------------------------------------------
    # Extract required strategy parameters
    # --------------------------------------------------------

    track = race_state.get(
        "Circuit"
    )

    tyre_compound = race_state.get(
        "TyreCompound"
    )

    current_lap = race_state.get(
        "CurrentLap"
    )

    laps_remaining = race_state.get(
        "LapsRemaining"
    )

    predicted_lap_time = race_state.get(
        "RecentPace"
    )

    # --------------------------------------------------------
    # Validate required simulation inputs
    # --------------------------------------------------------

    missing_inputs = []

    if track is None:

        missing_inputs.append(
            "Circuit"
        )

    if tyre_compound is None:

        missing_inputs.append(
            "TyreCompound"
        )

    if predicted_lap_time is None:

        missing_inputs.append(
            "RecentPace"
        )

    if laps_remaining is None:

        missing_inputs.append(
            "LapsRemaining"
        )

    if missing_inputs:

        raise ValueError(

            "Missing required strategy inputs: "

            + ", ".join(
                missing_inputs
            )

        )

    # --------------------------------------------------------
    # Run decision engine
    # --------------------------------------------------------

    decision_result = get_strategy_decision(

        track=track,

        driver=driver,

        tyre_compound=tyre_compound,

        predicted_lap_time=predicted_lap_time,

        laps_remaining=int(
            laps_remaining
        ),

        model_data=model_data

    )

    if not decision_result:

        raise RuntimeError(

            "Decision engine returned empty result."

        )

    print(
        "AI decision generated successfully."
    )

    # ========================================================
    # STEP 5 - BUILD FINAL RESULT
    # ========================================================

    print(
        "\n[5/5] Preparing final strategy result..."
    )

    result = {

        # ----------------------------------------------------
        # SESSION INFORMATION
        # ----------------------------------------------------

        "season":
            season,

        "grand_prix":
            grand_prix,

        "session_type":
            session_type,

        # ----------------------------------------------------
        # DRIVER INFORMATION
        # ----------------------------------------------------

        "driver":
            race_state.get(
                "Driver"
            ),

        "team":
            race_state.get(
                "Team"
            ),

        "driver_number":
            race_state.get(
                "DriverNumber"
            ),

        # ----------------------------------------------------
        # RACE STATE
        # ----------------------------------------------------

        "circuit":
            race_state.get(
                "Circuit"
            ),

        "current_lap":
            current_lap,

        "total_laps":
            race_state.get(
                "TotalLaps"
            ),

        "laps_remaining":
            laps_remaining,

        "race_progress":
            race_state.get(
                "RaceProgress"
            ),

        "position":
            race_state.get(
                "Position"
            ),

        # ----------------------------------------------------
        # TYRE STATE
        # ----------------------------------------------------

        "tyre_compound":
            race_state.get(
                "TyreCompound"
            ),

        "tyre_life":
            race_state.get(
                "TyreLife"
            ),

        "current_stint_length":
            race_state.get(
                "CurrentStintLength"
            ),

        "pit_stops_completed":
            race_state.get(
                "PitStopsCompleted"
            ),

        # ----------------------------------------------------
        # PACE
        # ----------------------------------------------------

        "recent_pace":
            race_state.get(
                "RecentPace"
            ),

        "average_pace":
            race_state.get(
                "AveragePace"
            ),

        "avg_pace_last_3":
            race_state.get(
                "AvgPaceLast3"
            ),

        "avg_pace_last_5":
            race_state.get(
                "AvgPaceLast5"
            ),

        "avg_pace_last_10":
            race_state.get(
                "AvgPaceLast10"
            ),

        "degradation_rate":
            race_state.get(
                "DegradationRate"
            ),

        # ----------------------------------------------------
        # ML + SIMULATION + FINAL DECISION
        # ----------------------------------------------------

        "pit_probability":
            decision_result.get(
                "pit_probability"
            ),

        "stay_out_time":
            decision_result.get(
                "stay_out_time"
            ),

        "pit_now_time":
            decision_result.get(
                "pit_now_time"
            ),

        "delta":
            decision_result.get(
                "delta"
            ),

        "simulator_recommendation":
            decision_result.get(
                "simulator_recommendation"
            ),

        "final_decision":
            decision_result.get(
                "final_decision"
            ),

        "confidence":
            decision_result.get(
                "confidence"
            ),

        "reason":
            decision_result.get(
                "reason"
            ),

        # ----------------------------------------------------
        # ML FEATURES
        # ----------------------------------------------------

        "model_features":
            model_data

    }

    return result


# ============================================================
# DISPLAY FINAL RESULT
# ============================================================

def display_strategy_result(
    result: Dict[str, Any]
):
    """
    Display the final AI strategy recommendation
    in a clean terminal format.
    """

    print(
        "\n"
        + "=" * 70
    )

    print(
        "F1 AI STRATEGIST"
    )

    print(
        "=" * 70
    )

    # --------------------------------------------------------
    # SESSION
    # --------------------------------------------------------

    print(
        "\nRACE INFORMATION"
    )

    print(
        "-" * 70
    )

    print(
        f"Season: "
        f"{result['season']}"
    )

    print(
        f"Grand Prix: "
        f"{result['grand_prix']}"
    )

    print(
        f"Circuit: "
        f"{result['circuit']}"
    )

    print(
        f"Session: "
        f"{result['session_type']}"
    )

    # --------------------------------------------------------
    # DRIVER
    # --------------------------------------------------------

    print(
        "\nDRIVER INFORMATION"
    )

    print(
        "-" * 70
    )

    print(
        f"Driver: "
        f"{result['driver']}"
    )

    print(
        f"Team: "
        f"{result['team']}"
    )

    print(
        f"Driver Number: "
        f"{result['driver_number']}"
    )

    # --------------------------------------------------------
    # RACE STATE
    # --------------------------------------------------------

    print(
        "\nCURRENT RACE STATE"
    )

    print(
        "-" * 70
    )

    print(
        f"Current Lap: "
        f"{result['current_lap']}"
    )

    print(
        f"Total Laps: "
        f"{result['total_laps']}"
    )

    print(
        f"Laps Remaining: "
        f"{result['laps_remaining']}"
    )

    print(
        f"Race Progress: "
        f"{result['race_progress']}"
    )

    print(
        f"Position: "
        f"{result['position']}"
    )

    # --------------------------------------------------------
    # TYRE
    # --------------------------------------------------------

    print(
        "\nTYRE INFORMATION"
    )

    print(
        "-" * 70
    )

    print(
        f"Compound: "
        f"{result['tyre_compound']}"
    )

    print(
        f"Tyre Life: "
        f"{result['tyre_life']}"
    )

    print(
        f"Current Stint Length: "
        f"{result['current_stint_length']}"
    )

    print(
        f"Pit Stops Completed: "
        f"{result['pit_stops_completed']}"
    )

    # --------------------------------------------------------
    # PACE
    # --------------------------------------------------------

    print(
        "\nPACE ANALYSIS"
    )

    print(
        "-" * 70
    )

    print(
        f"Recent Pace: "
        f"{result['recent_pace']}"
    )

    print(
        f"Average Pace: "
        f"{result['average_pace']}"
    )

    print(
        f"Average Pace Last 3: "
        f"{result['avg_pace_last_3']}"
    )

    print(
        f"Average Pace Last 5: "
        f"{result['avg_pace_last_5']}"
    )

    print(
        f"Average Pace Last 10: "
        f"{result['avg_pace_last_10']}"
    )

    print(
        f"Degradation Rate: "
        f"{result['degradation_rate']}"
    )

    # --------------------------------------------------------
    # ML PREDICTION
    # --------------------------------------------------------

    print(
        "\nML PREDICTION"
    )

    print(
        "-" * 70
    )

    print(
        f"Pit Probability: "
        f"{result['pit_probability']}%"
    )

    # --------------------------------------------------------
    # STRATEGY SIMULATION
    # --------------------------------------------------------

    print(
        "\nSTRATEGY SIMULATION"
    )

    print(
        "-" * 70
    )

    print(
        f"Stay Out Time: "
        f"{result['stay_out_time']}"
    )

    print(
        f"Pit Now Time: "
        f"{result['pit_now_time']}"
    )

    print(
        f"Time Delta: "
        f"{result['delta']}"
    )

    print(
        f"Simulator Recommendation: "
        f"{result['simulator_recommendation']}"
    )

    # --------------------------------------------------------
    # FINAL DECISION
    # --------------------------------------------------------

    print(
        "\nFINAL AI DECISION"
    )

    print(
        "=" * 70
    )

    print(
        f"Decision: "
        f"{result['final_decision']}"
    )

    print(
        f"Confidence: "
        f"{result['confidence']}"
    )

    print(
        "\nReason:"
    )

    print(
        result['reason']
    )

    print(
        "\n"
        + "=" * 70
    )


# ============================================================
# TEST CONFIGURATION
# ============================================================

if __name__ == "__main__":

    SEASON = 2025

    GRAND_PRIX = (
        "British Grand Prix"
    )

    DRIVER = "VER"

    SESSION_TYPE = "R"

    THRESHOLD = 50.0

    # ========================================================
    # RUN PIPELINE
    # ========================================================

    print(
        "=" * 70
    )

    print(
        "V5 SPRINT 2 - END-TO-END STRATEGY PIPELINE TEST"
    )

    print(
        "=" * 70
    )

    try:

        result = run_strategy_pipeline(

            season=SEASON,

            grand_prix=GRAND_PRIX,

            driver=DRIVER,

            session_type=SESSION_TYPE,

            threshold=THRESHOLD

        )

        # ----------------------------------------------------
        # DISPLAY RESULT
        # ----------------------------------------------------

        display_strategy_result(
            result
        )

        print(
            "\n✅ END-TO-END PIPELINE TEST PASSED"
        )

    except Exception as e:

        print(
            "\n❌ END-TO-END PIPELINE TEST FAILED"
        )

        print(
            f"Error: {e}"
        )

        raise