import os

import pandas as pd

from xgboost import XGBClassifier


# ============================================================
# MODEL PATH
# ============================================================

MODEL_PATH = os.path.join(

    os.path.dirname(

        os.path.dirname(

            os.path.abspath(__file__)

        )

    ),

    "models",

    "pit_strategy_model.json"

)


# ============================================================
# LOAD MODEL
# ============================================================

def load_model():
    """
    Load the trained XGBoost model
    using native JSON format.
    """

    if not os.path.exists(
        MODEL_PATH
    ):

        raise FileNotFoundError(

            f"Model not found at {MODEL_PATH}. "
            "Run the training pipeline first."

        )


    model = XGBClassifier()


    model.load_model(
        MODEL_PATH
    )


    return model


# ============================================================
# PREDICT PIT PROBABILITY
# ============================================================

def predict_pit_probability(
    model_data
):
    """
    Predict the probability of a pit stop
    using the trained XGBoost model.

    Parameters
    ----------
    model_data : dict or pandas.DataFrame
        ML features generated by the feature
        engineering pipeline.

    Returns
    -------
    float
        Pit stop probability in percentage.
    """

    # --------------------------------------------------------
    # Load trained model
    # --------------------------------------------------------

    model = load_model()


    # --------------------------------------------------------
    # Convert input into DataFrame
    # --------------------------------------------------------

    if isinstance(
        model_data,
        dict
    ):

        X = pd.DataFrame(
            [model_data]
        )

    elif isinstance(
        model_data,
        pd.DataFrame
    ):

        X = model_data.copy()

    else:

        raise TypeError(

            "model_data must be a dictionary "
            "or pandas DataFrame."

        )


    # --------------------------------------------------------
    # Get model feature names
    # --------------------------------------------------------

    if hasattr(
        model,
        "feature_names_in_"
    ):

        expected_features = list(
            model.feature_names_in_
        )

    else:

        expected_features = list(
            X.columns
        )


    # --------------------------------------------------------
    # Validate required features
    # --------------------------------------------------------

    missing_features = [

        feature

        for feature in expected_features

        if feature not in X.columns

    ]


    if missing_features:

        raise ValueError(

            "Missing model features: "

            + ", ".join(
                missing_features
            )

        )


    # --------------------------------------------------------
    # Select features in correct order
    # --------------------------------------------------------

    X = X[
        expected_features
    ]


    # --------------------------------------------------------
    # Convert values to numeric
    # --------------------------------------------------------

    X = X.apply(
        pd.to_numeric,
        errors="coerce"
    )


    # --------------------------------------------------------
    # Handle missing values
    # --------------------------------------------------------

    if X.isnull().any().any():

        missing_columns = list(

            X.columns[
                X.isnull().any()
            ]

        )

        raise ValueError(

            "Model input contains missing "
            "or non-numeric values in: "

            + ", ".join(
                missing_columns
            )

        )


    # --------------------------------------------------------
    # Predict probability
    # --------------------------------------------------------

    probabilities = model.predict_proba(
        X
    )


    # --------------------------------------------------------
    # Extract PIT probability
    # --------------------------------------------------------

    if probabilities.shape[1] < 2:

        raise RuntimeError(

            "XGBoost model does not contain "
            "two probability classes."

        )


    pit_probability = (

        probabilities[
            0,
            1
        ]

        * 100

    )


    # --------------------------------------------------------
    # Safety bounds
    # --------------------------------------------------------

    pit_probability = max(

        0.0,

        min(

            100.0,

            float(
                pit_probability
            )

        )

    )


    return pit_probability


# ============================================================
# ML RECOMMENDATION
# ============================================================

def get_ml_recommendation(
    pit_probability: float
):
    """
    Convert the predicted pit probability
    into a simple ML recommendation.

    Probability >= 60%
        -> PIT NOW

    Probability <= 40%
        -> STAY OUT

    Otherwise
        -> UNCERTAIN
    """

    if not isinstance(
        pit_probability,
        (int, float)
    ):

        raise TypeError(

            "pit_probability must be "
            "a numeric value."

        )


    if pit_probability >= 60:

        return "PIT NOW"


    elif pit_probability <= 40:

        return "STAY OUT"


    else:

        return "UNCERTAIN"