import os
import joblib
import pandas as pd


# ============================================================
# MODEL PATH
# ============================================================

MODEL_PATH = os.path.join(
    os.path.dirname(
        os.path.dirname(
            os.path.abspath(__file__)
        )
    ),
    "models",
    "pit_strategy_model.pkl"
)


# ============================================================
# LOAD MODEL
# ============================================================

def load_model():
    """
    Load the trained pit strategy model.

    Returns
    -------
    model
        Trained ML model loaded from the models directory.
    """

    if not os.path.exists(
        MODEL_PATH
    ):

        raise FileNotFoundError(

            f"Model not found at "
            f"{MODEL_PATH}. "

            "Run the training pipeline first."

        )

    return joblib.load(
        MODEL_PATH
    )


# ============================================================
# PREDICT PIT PROBABILITY
# ============================================================

def predict_pit_probability(
    data: pd.DataFrame
):
    """
    Predict the probability that the driver
    will pit on the next lap.

    Parameters
    ----------
    data : pandas.DataFrame
        DataFrame containing the 11 ML features.

    Returns
    -------
    float
        Pit probability as a percentage.
    """

    if not isinstance(
        data,
        pd.DataFrame
    ):

        raise TypeError(
            "data must be a pandas DataFrame."
        )

    model = load_model()

    probability = (

        model.predict_proba(
            data
        )[0][1]

    )

    return round(
        probability * 100,
        2
    )


# ============================================================
# PREDICT PIT DECISION
# ============================================================

def predict_pit_decision(
    data: pd.DataFrame,
    threshold: float = 50.0
):
    """
    Predict whether the model expects the driver
    to pit on the next lap.

    NOTE:
    This is the raw ML prediction only.

    The final strategic decision will later be
    handled by decision_engine.py after considering
    the strategy simulator.

    Parameters
    ----------
    data : pandas.DataFrame
        DataFrame containing the 11 ML features.

    threshold : float
        Probability threshold for the PIT decision.

    Returns
    -------
    dict
        Prediction result.
    """

    probability = (

        predict_pit_probability(
            data
        )

    )

    if probability >= threshold:

        decision = "PIT"

    else:

        decision = "STAY"

    return {

        "pit_probability":
            probability,

        "decision":
            decision

    }


# ============================================================
# V5 DYNAMIC RACE STATE PREDICTION
# ============================================================

def predict_from_race_state(
    race_state: dict,
    threshold: float = 50.0
):
    """
    Run the complete V5 dynamic prediction pipeline.

    Pipeline:

        Race State
             ↓
        Feature Engineering
             ↓
        ML Feature Validation
             ↓
        Trained XGBoost Model
             ↓
        Pit Probability
             ↓
        Raw ML Decision

    Parameters
    ----------
    race_state : dict
        Structured race state generated by race_state.py.

    threshold : float
        Probability threshold used for the raw ML prediction.

    Returns
    -------
    dict
        Complete prediction result.
    """

    # Import here to avoid unnecessary dependency
    # when this module is only used for model loading.
    from src.feature_engineering import (
        build_ml_features,
        validate_ml_features
    )

    # --------------------------------------------------------
    # Build ML features
    # --------------------------------------------------------

    features = build_ml_features(
        race_state
    )

    # --------------------------------------------------------
    # Validate ML features
    # --------------------------------------------------------

    validate_ml_features(
        features
    )

    # --------------------------------------------------------
    # Predict
    # --------------------------------------------------------

    prediction = predict_pit_decision(
        features,
        threshold=threshold
    )

    # --------------------------------------------------------
    # Add race information to result
    # --------------------------------------------------------

    result = {

        "driver":
            race_state.get(
                "Driver"
            ),

        "team":
            race_state.get(
                "Team"
            ),

        "current_lap":
            race_state.get(
                "CurrentLap"
            ),

        "position":
            race_state.get(
                "Position"
            ),

        "tyre_compound":
            race_state.get(
                "TyreCompound"
            ),

        "tyre_life":
            race_state.get(
                "TyreLife"
            ),

        "pit_probability":
            prediction[
                "pit_probability"
            ],

        "decision":
            prediction[
                "decision"
            ],

        "features":
            features

    }

    return result


# ============================================================
# TESTING
# ============================================================

if __name__ == "__main__":

    from src.data_loader import (
        load_session
    )

    from src.race_state import (
        build_race_state
    )


    # --------------------------------------------------------
    # TEST CONFIGURATION
    # --------------------------------------------------------

    SEASON = 2025

    GRAND_PRIX = (
        "British Grand Prix"
    )

    SESSION_TYPE = "R"

    DRIVER = "VER"


    # --------------------------------------------------------
    # LOAD SESSION
    # --------------------------------------------------------

    print(
        "=" * 60
    )

    print(
        "V5 SPRINT 1 - STEP 4 PREDICTION TEST"
    )

    print(
        "=" * 60
    )

    print(
        "\nLoading FastF1 session..."
    )

    session = load_session(

        SEASON,

        GRAND_PRIX,

        SESSION_TYPE

    )

    print(
        "Session loaded successfully."
    )


    # --------------------------------------------------------
    # BUILD RACE STATE
    # --------------------------------------------------------

    print(
        "\nBuilding race state..."
    )

    race_state = build_race_state(

        session,

        DRIVER

    )

    print(
        "Race state generated successfully."
    )


    # --------------------------------------------------------
    # RUN PREDICTION
    # --------------------------------------------------------

    print(
        "\nRunning ML prediction..."
    )

    result = predict_from_race_state(

        race_state

    )


    # --------------------------------------------------------
    # DISPLAY RESULT
    # --------------------------------------------------------

    print(
        "\n" + "=" * 60
    )

    print(
        "V5 AI PIT STRATEGY PREDICTION"
    )

    print(
        "=" * 60
    )

    print(
        f"Driver: "
        f"{result['driver']}"
    )

    print(
        f"Team: "
        f"{result['team']}"
    )

    print(
        f"Current Lap: "
        f"{result['current_lap']}"
    )

    print(
        f"Position: "
        f"{result['position']}"
    )

    print(
        f"Tyre: "
        f"{result['tyre_compound']}"
    )

    print(
        f"Tyre Life: "
        f"{result['tyre_life']}"
    )

    print(
        f"Pit Probability: "
        f"{result['pit_probability']}%"
    )

    print(
        f"Raw ML Decision: "
        f"{result['decision']}"
    )

    print(
        "=" * 60
    )

    print(
        "\nStep 4 prediction test completed."
    )